
#include "bfd_headers.h"
#include <stdio.h>

#define py_comment_ml(cmt) fprintf(fd, "#\n# " cmt "\n#\n");

#define py_empty_line fprintf(fd, "\n");

#define py_const_def(c,v) fprintf(fd, #c " = %d\n", v);

//
// Name : write_architectures_constants
//
void write_architectures_constants(FILE* fd)
{
    py_comment_ml("Supported architectures.")

    py_const_def(ARCH_M68K, bfd_arch_m68k)
    py_const_def(ARCH_VAX, bfd_arch_vax)
    py_const_def(ARCH_I960, bfd_arch_i960)
    py_const_def(ARCH_OR32, bfd_arch_or32)
    py_const_def(ARCH_SPARC, bfd_arch_sparc)
    py_const_def(ARCH_SPU, bfd_arch_spu)
    py_const_def(ARCH_MIPS, bfd_arch_mips)
    py_const_def(ARCH_I386, bfd_arch_i386)
    py_const_def(ARCH_L1OM, bfd_arch_l1om)
    py_const_def(ARCH_K1OM, bfd_arch_k1om)
    py_const_def(ARCH_I860, bfd_arch_i860)
    py_const_def(ARCH_I370, bfd_arch_i370)
    py_const_def(ARCH_M88K, bfd_arch_m88k)
    py_const_def(ARCH_H8300, bfd_arch_h8300)
    py_const_def(ARCH_PDP11, bfd_arch_pdp11)
    py_const_def(ARCH_POWERPC, bfd_arch_powerpc)
    py_const_def(ARCH_RS6000, bfd_arch_rs6000)
    py_const_def(ARCH_HPPA, bfd_arch_hppa)
    py_const_def(ARCH_D10V, bfd_arch_d10v)
    py_const_def(ARCH_D30V, bfd_arch_d30v)
    py_const_def(ARCH_DLX, bfd_arch_dlx)
    py_const_def(ARCH_M68HC11, bfd_arch_m68hc11)
    py_const_def(ARCH_Z8K, bfd_arch_z8k)
    py_const_def(ARCH_H8500, bfd_arch_h8500)
    py_const_def(ARCH_SH, bfd_arch_sh)
    py_const_def(ARCH_ALPHA, bfd_arch_alpha)
    py_const_def(ARCH_ARM, bfd_arch_arm)
    py_const_def(ARCH_NS32K, bfd_arch_ns32k)
    py_const_def(ARCH_W65, bfd_arch_w65)
    py_const_def(ARCH_TIC30, bfd_arch_tic30)
    py_const_def(ARCH_TIC4X, bfd_arch_tic4x)
    py_const_def(ARCH_TIC54X, bfd_arch_tic54x)
    py_const_def(ARCH_TIC6X, bfd_arch_tic6x)
    py_const_def(ARCH_TIC80, bfd_arch_tic80)
    py_const_def(ARCH_M32C, bfd_arch_m32c)
    py_const_def(ARCH_M32R, bfd_arch_m32r)
    py_const_def(ARCH_MN10200, bfd_arch_mn10200)
    py_const_def(ARCH_MN10300, bfd_arch_mn10300)
    py_const_def(ARCH_FR30, bfd_arch_fr30)
    py_const_def(ARCH_FRV, bfd_arch_frv)
    py_const_def(ARCH_MOXIE, bfd_arch_moxie)
    py_const_def(ARCH_MCORE, bfd_arch_mcore)
    py_const_def(ARCH_MEP, bfd_arch_mep)
    py_const_def(ARCH_IA64, bfd_arch_ia64)
    py_const_def(ARCH_IQ2000, bfd_arch_iq2000)
    py_const_def(ARCH_MT, bfd_arch_mt)
    py_const_def(ARCH_PJ, bfd_arch_pj)
    py_const_def(ARCH_AVR, bfd_arch_avr)
    py_const_def(ARCH_BFIN, bfd_arch_bfin)
    py_const_def(ARCH_CR16C, bfd_arch_cr16c)
    py_const_def(ARCH_CRX, bfd_arch_crx)
    py_const_def(ARCH_RX, bfd_arch_rx)
    py_const_def(ARCH_S390, bfd_arch_s390)
    py_const_def(ARCH_SCORE, bfd_arch_score)
    py_const_def(ARCH_OPENRISC, bfd_arch_openrisc)
    py_const_def(ARCH_MMIX, bfd_arch_mmix)
    py_const_def(ARCH_XSTORMY16, bfd_arch_xstormy16)
    py_const_def(ARCH_MSP430, bfd_arch_msp430)
    py_const_def(ARCH_XC16X, bfd_arch_xc16x)
    py_const_def(ARCH_XTENSA, bfd_arch_xtensa)
    py_const_def(ARCH_Z80, bfd_arch_z80)
    py_const_def(ARCH_LM32, bfd_arch_lm32)
    py_const_def(ARCH_MICROBLAZE, bfd_arch_microblaze)
    py_const_def(ARCH_TILEPRO, bfd_arch_tilepro)
    py_const_def(ARCH_TILEGX, bfd_arch_tilegx)
    py_const_def(ARCH_AARCH64, bfd_arch_aarch64)
    py_const_def(ARCH_RL78, bfd_arch_rl78)
}

//
// Name : write_endianess_constants
//
void write_endianess_constants(FILE* fd)
{
    py_comment_ml("Supported endianess.")

    py_const_def(ENDIAN_BIG      , BFD_ENDIAN_BIG)
    py_const_def(ENDIAN_LITTLE   , BFD_ENDIAN_LITTLE)
    py_const_def(ENDIAN_UNKNOWN  , BFD_ENDIAN_UNKNOWN)
    py_const_def(ENDIAN_MONO     , BFD_ENDIAN_UNKNOWN)

    py_empty_line
}

//
// Name : write_machines_constants
//
void write_machines_constants(FILE* fd)
{
    py_comment_ml("Supported machines")

    py_const_def(MACH_M68000, 1)
    py_const_def(MACH_M68008, 2)
    py_const_def(MACH_M68010, 3)
    py_const_def(MACH_M68020, 4)
    py_const_def(MACH_M68030, 5)
    py_const_def(MACH_M68040, 6)
    py_const_def(MACH_M68060, 7)
    py_const_def(MACH_CPU32, 8)
    py_const_def(MACH_FIDO, 9)
    py_const_def(MACH_MCF_ISA_A_NODIV, 10)
    py_const_def(MACH_MCF_ISA_A, 11)
    py_const_def(MACH_MCF_ISA_A_MAC, 12)
    py_const_def(MACH_MCF_ISA_A_EMAC, 13)
    py_const_def(MACH_MCF_ISA_APLUS, 14)
    py_const_def(MACH_MCF_ISA_APLUS_MAC, 15)
    py_const_def(MACH_MCF_ISA_APLUS_EMAC, 16)
    py_const_def(MACH_MCF_ISA_B_NOUSP, 17)
    py_const_def(MACH_MCF_ISA_B_NOUSP_MAC, 18)
    py_const_def(MACH_MCF_ISA_B_NOUSP_EMAC, 19)
    py_const_def(MACH_MCF_ISA_B, 20)
    py_const_def(MACH_MCF_ISA_B_MAC, 21)
    py_const_def(MACH_MCF_ISA_B_EMAC, 22)
    py_const_def(MACH_MCF_ISA_B_FLOAT, 23)
    py_const_def(MACH_MCF_ISA_B_FLOAT_MAC, 24)
    py_const_def(MACH_MCF_ISA_B_FLOAT_EMAC, 25)
    py_const_def(MACH_MCF_ISA_C, 26)
    py_const_def(MACH_MCF_ISA_C_MAC, 27)
    py_const_def(MACH_MCF_ISA_C_EMAC, 28)
    py_const_def(MACH_MCF_ISA_C_NODIV, 29)
    py_const_def(MACH_MCF_ISA_C_NODIV_MAC, 30)
    py_const_def(MACH_MCF_ISA_C_NODIV_EMAC, 31)
    py_const_def(MACH_I960_CORE, 1)
    py_const_def(MACH_I960_KA_SA, 2)
    py_const_def(MACH_I960_KB_SB, 3)
    py_const_def(MACH_I960_MC, 4)
    py_const_def(MACH_I960_XA, 5)
    py_const_def(MACH_I960_CA, 6)
    py_const_def(MACH_I960_JX, 7)
    py_const_def(MACH_I960_HX, 8)
    py_const_def(MACH_SPARC, 1)
    py_const_def(MACH_SPARC_SPARCLET, 2)
    py_const_def(MACH_SPARC_SPARCLITE, 3)
    py_const_def(MACH_SPARC_V8PLUS, 4)
    py_const_def(MACH_SPARC_V8PLUSA, 5 /* with ultrasparc add'ns.  */)
    py_const_def(MACH_SPARC_SPARCLITE_LE, 6)
    py_const_def(MACH_SPARC_V9, 7)
    py_const_def(MACH_SPARC_V9A, 8 /* with ultrasparc add'ns.  */)
    py_const_def(MACH_SPARC_V8PLUSB, 9 /* with cheetah add'ns.  */)
    py_const_def(MACH_SPARC_V9B, 10 /* with cheetah add'ns.  */)
    py_const_def(MACH_SPU, 256 )
    py_const_def(MACH_MIPS3000, 3000)
    py_const_def(MACH_MIPS3900, 3900)
    py_const_def(MACH_MIPS4000, 4000)
    py_const_def(MACH_MIPS4010, 4010)
    py_const_def(MACH_MIPS4100, 4100)
    py_const_def(MACH_MIPS4111, 4111)
    py_const_def(MACH_MIPS4120, 4120)
    py_const_def(MACH_MIPS4300, 4300)
    py_const_def(MACH_MIPS4400, 4400)
    py_const_def(MACH_MIPS4600, 4600)
    py_const_def(MACH_MIPS4650, 4650)
    py_const_def(MACH_MIPS5000, 5000)
    py_const_def(MACH_MIPS5400, 5400)
    py_const_def(MACH_MIPS5500, 5500)
    py_const_def(MACH_MIPS6000, 6000)
    py_const_def(MACH_MIPS7000, 7000)
    py_const_def(MACH_MIPS8000, 8000)
    py_const_def(MACH_MIPS9000, 9000)
    py_const_def(MACH_MIPS10000, 10000)
    py_const_def(MACH_MIPS12000, 12000)
    py_const_def(MACH_MIPS14000, 14000)
    py_const_def(MACH_MIPS16000, 16000)
    py_const_def(MACH_MIPS16, 16)
    py_const_def(MACH_MIPS5, 5)
    py_const_def(MACH_MIPS_LOONGSON_2E, 3001)
    py_const_def(MACH_MIPS_LOONGSON_2F, 3002)
    py_const_def(MACH_MIPS_LOONGSON_3A, 3003)
    py_const_def(MACH_MIPS_SB1, 12310201 /* octal 'SB', 01 */)
    py_const_def(MACH_MIPS_OCTEON, 6501)
    py_const_def(MACH_MIPS_OCTEONP, 6601)
    py_const_def(MACH_MIPS_OCTEON2, 6502)
    py_const_def(MACH_MIPS_XLR, 887682   /* decimal 'XLR'  */)
    py_const_def(MACH_MIPSISA32, 32)
    py_const_def(MACH_MIPSISA32R2, 33)
    py_const_def(MACH_MIPSISA64, 64)
    py_const_def(MACH_MIPSISA64R2, 65)
    py_const_def(MACH_MIPS_MICROMIPS, 96)
    py_const_def(MACH_I386_INTEL_SYNTAX, (1 << 0))
    py_const_def(MACH_I386_I8086, (1 << 1))
    py_const_def(MACH_I386_I386, (1 << 2))
    py_const_def(MACH_X86_64, (1 << 3))
    py_const_def(MACH_X64_32, (1 << 4))
    py_const_def(MACH_I386_I386_INTEL_SYNTAX, (bfd_mach_i386_i386 | bfd_mach_i386_intel_syntax))
    py_const_def(MACH_X86_64_INTEL_SYNTAX, (bfd_mach_x86_64 | bfd_mach_i386_intel_syntax))
    py_const_def(MACH_X64_32_INTEL_SYNTAX, (bfd_mach_x64_32 | bfd_mach_i386_intel_syntax))
    py_const_def(MACH_L1OM, (1 << 5))
    py_const_def(MACH_L1OM_INTEL_SYNTAX, (bfd_mach_l1om | bfd_mach_i386_intel_syntax))
    py_const_def(MACH_K1OM, (1 << 6))
    py_const_def(MACH_K1OM_INTEL_SYNTAX, (bfd_mach_k1om | bfd_mach_i386_intel_syntax))
    py_const_def(MACH_H8300, 1)
    py_const_def(MACH_H8300H, 2)
    py_const_def(MACH_H8300S, 3)
    py_const_def(MACH_H8300HN, 4)
    py_const_def(MACH_H8300SN, 5)
    py_const_def(MACH_H8300SX, 6)
    py_const_def(MACH_H8300SXN, 7)
    py_const_def(MACH_PPC, 32)
    py_const_def(MACH_PPC64, 64)
    py_const_def(MACH_PPC_403, 403)
    py_const_def(MACH_PPC_403GC, 4030)
    py_const_def(MACH_PPC_405, 405)
    py_const_def(MACH_PPC_505, 505)
    py_const_def(MACH_PPC_601, 601)
    py_const_def(MACH_PPC_602, 602)
    py_const_def(MACH_PPC_603, 603)
    py_const_def(MACH_PPC_EC603E, 6031)
    py_const_def(MACH_PPC_604, 604)
    py_const_def(MACH_PPC_620, 620)
    py_const_def(MACH_PPC_630, 630)
    py_const_def(MACH_PPC_750, 750)
    py_const_def(MACH_PPC_860, 860)
    py_const_def(MACH_PPC_A35, 35)
    py_const_def(MACH_PPC_RS64II, 642)
    py_const_def(MACH_PPC_RS64III, 643)
    py_const_def(MACH_PPC_7400, 7400)
    py_const_def(MACH_PPC_E500, 500)
    py_const_def(MACH_PPC_E500MC, 5001)
    py_const_def(MACH_PPC_E500MC64, 5005)
    py_const_def(MACH_PPC_E5500, 5006)
    py_const_def(MACH_PPC_E6500, 5007)
    py_const_def(MACH_PPC_TITAN, 83)
    py_const_def(MACH_PPC_VLE, 84)
    py_const_def(MACH_RS6K, 6000)
    py_const_def(MACH_RS6K_RS1, 6001)
    py_const_def(MACH_RS6K_RSC, 6003)
    py_const_def(MACH_RS6K_RS2, 6002)
    py_const_def(MACH_HPPA10, 10)
    py_const_def(MACH_HPPA11, 11)
    py_const_def(MACH_HPPA20, 20)
    py_const_def(MACH_HPPA20W, 25)
    py_const_def(MACH_D10V, 1)
    py_const_def(MACH_D10V_TS2, 2)
    py_const_def(MACH_D10V_TS3, 3)
    py_const_def(MACH_M6812_DEFAULT, 0)
    py_const_def(MACH_M6812, 1)
    py_const_def(MACH_M6812S, 2)
    py_const_def(MACH_Z8001, 1)
    py_const_def(MACH_Z8002, 2)
    py_const_def(MACH_SH, 1)
    py_const_def(MACH_SH2, 0x20)
    py_const_def(MACH_SH_DSP, 0x2d)
    py_const_def(MACH_SH2A, 0x2a)
    py_const_def(MACH_SH2A_NOFPU, 0x2b)
    py_const_def(MACH_SH2A_NOFPU_OR_SH4_NOMMU_NOFPU, 0x2a1)
    py_const_def(MACH_SH2A_NOFPU_OR_SH3_NOMMU, 0x2a2)
    py_const_def(MACH_SH2A_OR_SH4, 0x2a3)
    py_const_def(MACH_SH2A_OR_SH3E, 0x2a4)
    py_const_def(MACH_SH2E, 0x2e)
    py_const_def(MACH_SH3, 0x30)
    py_const_def(MACH_SH3_NOMMU, 0x31)
    py_const_def(MACH_SH3_DSP, 0x3d)
    py_const_def(MACH_SH3E, 0x3e)
    py_const_def(MACH_SH4, 0x40)
    py_const_def(MACH_SH4_NOFPU, 0x41)
    py_const_def(MACH_SH4_NOMMU_NOFPU, 0x42)
    py_const_def(MACH_SH4A, 0x4a)
    py_const_def(MACH_SH4A_NOFPU, 0x4b)
    py_const_def(MACH_SH4AL_DSP, 0x4d)
    py_const_def(MACH_SH5, 0x50)
    py_const_def(MACH_ALPHA_EV4, 0x10)
    py_const_def(MACH_ALPHA_EV5, 0x20)
    py_const_def(MACH_ALPHA_EV6, 0x30)
    py_const_def(MACH_ARM_UNKNOWN, 0)
    py_const_def(MACH_ARM_2, 1)
    py_const_def(MACH_ARM_2A, 2)
    py_const_def(MACH_ARM_3, 3)
    py_const_def(MACH_ARM_3M, 4)
    py_const_def(MACH_ARM_4, 5)
    py_const_def(MACH_ARM_4T, 6)
    py_const_def(MACH_ARM_5, 7)
    py_const_def(MACH_ARM_5T, 8)
    py_const_def(MACH_ARM_5TE, 9)
    py_const_def(MACH_ARM_XSCALE, 10)
    py_const_def(MACH_ARM_EP9312, 11)
    py_const_def(MACH_ARM_IWMMXT, 12)
    py_const_def(MACH_ARM_IWMMXT2, 13)
    py_const_def(MACH_TIC3X, 30)
    py_const_def(MACH_TIC4X, 40)
    py_const_def(MACH_V850, 1)
    py_const_def(MACH_V850E, 'E')
    py_const_def(MACH_V850E1, '1')
    py_const_def(MACH_V850E2, 0x4532)
    py_const_def(MACH_V850E2V3, 0x45325633)
    py_const_def(MACH_ARC_5, 5)
    py_const_def(MACH_ARC_6, 6)
    py_const_def(MACH_ARC_7, 7)
    py_const_def(MACH_ARC_8, 8)
    py_const_def(MACH_M16C, 0x75)
    py_const_def(MACH_M32C, 0x78)
    py_const_def(MACH_M32R, 1 /* For backwards compatibility.  */)
    py_const_def(MACH_M32RX, 'x')
    py_const_def(MACH_M32R2, '2')
    py_const_def(MACH_MN10300, 300)
    py_const_def(MACH_AM33, 330)
    py_const_def(MACH_AM33_2, 332)
    py_const_def(MACH_FR30, 0x46523330)
    py_const_def(MACH_FRV, 1)
    py_const_def(MACH_FRVSIMPLE, 2)
    py_const_def(MACH_FR300, 300)
    py_const_def(MACH_FR400, 400)
    py_const_def(MACH_FR450, 450)
    py_const_def(MACH_FRVTOMCAT, 499     /* fr500 prototype */)
    py_const_def(MACH_FR500, 500)
    py_const_def(MACH_FR550, 550)
    py_const_def(MACH_MOXIE, 1)
    py_const_def(MACH_MEP, 1)
    py_const_def(MACH_MEP_H1, 0x6831)
    py_const_def(MACH_MEP_C5, 0x6335)
    py_const_def(MACH_IA64_ELF64, 64)
    py_const_def(MACH_IA64_ELF32, 32)
    py_const_def(MACH_IP2022, 1)
    py_const_def(MACH_IP2022EXT, 2)
    py_const_def(MACH_IQ2000, 1)
    py_const_def(MACH_IQ10, 2)
    py_const_def(MACH_EPIPHANY16, 1)
    py_const_def(MACH_EPIPHANY32, 2)
    py_const_def(MACH_MS1, 1)
    py_const_def(MACH_MRISC2, 2)
    py_const_def(MACH_MS2, 3)
    py_const_def(MACH_AVR1, 1)
    py_const_def(MACH_AVR2, 2)
    py_const_def(MACH_AVR25, 25)
    py_const_def(MACH_AVR3, 3)
    py_const_def(MACH_AVR31, 31)
    py_const_def(MACH_AVR35, 35)
    py_const_def(MACH_AVR4, 4)
    py_const_def(MACH_AVR5, 5)
    py_const_def(MACH_AVR51, 51)
    py_const_def(MACH_AVR6, 6)
    py_const_def(MACH_AVRXMEGA1, 101)
    py_const_def(MACH_AVRXMEGA2, 102)
    py_const_def(MACH_AVRXMEGA3, 103)
    py_const_def(MACH_AVRXMEGA4, 104)
    py_const_def(MACH_AVRXMEGA5, 105)
    py_const_def(MACH_AVRXMEGA6, 106)
    py_const_def(MACH_AVRXMEGA7, 107)
    py_const_def(MACH_BFIN, 1)
    py_const_def(MACH_CR16, 1)
    py_const_def(MACH_CR16C, 1)
    py_const_def(MACH_CRX, 1)
    py_const_def(MACH_CRIS_V0_V10, 255)
    py_const_def(MACH_CRIS_V32, 32)
    py_const_def(MACH_CRIS_V10_V32, 1032)
    py_const_def(MACH_RL78, 0x75)
    py_const_def(MACH_RX, 0x75)
    py_const_def(MACH_S390_31, 31)
    py_const_def(MACH_S390_64, 64)
    py_const_def(MACH_SCORE3, 3)
    py_const_def(MACH_SCORE7, 7)
    py_const_def(MACH_XSTORMY16, 1)
    py_const_def(MACH_MSP11, 11)
    py_const_def(MACH_MSP110, 110)
    py_const_def(MACH_MSP12, 12)
    py_const_def(MACH_MSP13, 13)
    py_const_def(MACH_MSP14, 14)
    py_const_def(MACH_MSP15, 15)
    py_const_def(MACH_MSP16, 16)
    py_const_def(MACH_MSP21, 21)
    py_const_def(MACH_MSP31, 31)
    py_const_def(MACH_MSP32, 32)
    py_const_def(MACH_MSP33, 33)
    py_const_def(MACH_MSP41, 41)
    py_const_def(MACH_MSP42, 42)
    py_const_def(MACH_MSP43, 43)
    py_const_def(MACH_MSP44, 44)
    py_const_def(MACH_XC16X, 1)
    py_const_def(MACH_XC16XL, 2)
    py_const_def(MACH_XC16XS, 3)
    py_const_def(MACH_XGATE, 1)
    py_const_def(MACH_XTENSA, 1)
    py_const_def(MACH_Z80STRICT, 1 /* No undocumented opcodes.  */)
    py_const_def(MACH_Z80, 3 /* With ixl, ixh, iyl, and iyh.  */)
    py_const_def(MACH_Z80FULL, 7 /* All undocumented instructions.  */)
    py_const_def(MACH_R800, 11 /* R800: successor with multiplication.  */)
    py_const_def(MACH_LM32, 1)
    py_const_def(MACH_TILEPRO, 1)
    py_const_def(MACH_TILEGX, 1)
    py_const_def(MACH_TILEGX32, 2)
    py_const_def(MACH_AARCH64, 0)
}

//
// Name : main
//
int main(int argc, char* argv[])
//int _start(int argc, char** argv[])
{
    FILE *fd = stdout;
    //
    // Step 1. Create file header.
    //
    py_comment_ml("This file was automagically generated.")

    //
    // Step 2. Create architectures list.
    //
    write_architectures_constants(fd);

    //
    // Step 3. Create endian list.
    //
    write_endianess_constants(fd);

    //
    // Step 4. Create machines list.
    //
    write_machines_constants(fd);

    fclose(fd);

    return 0;
}

